apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-dmarc-analyzer.fullname" . }}-analyzer-secret
  labels:
  {{- include "open-dmarc-analyzer.labels" . | nindent 4 }}
data:
  DB_HOST: {{ printf "%s-mariadb" (include "open-dmarc-analyzer.fullname" .) | b64enc | quote }}
  DB_NAME: {{ .Values.mariadb.config.mariadbDatabase | b64enc | quote }}
  DB_PASS: {{ .Values.mariadb.config.mariadbPassword | b64enc | quote }}
  DB_USER: {{ .Values.mariadb.config.mariadbUser | b64enc | quote }}
  GEO_ENABLE: {{ .Values.analyzer.config.geoEnable | b64enc | quote }}