apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-dmarc-analyzer.fullname" . }}-mariadb
  labels:
    io.kompose.service: analyzer
  {{- include "open-dmarc-analyzer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.analyzer.type }}
  selector:
    io.kompose.service: analyzer
    {{- include "open-dmarc-analyzer.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mariadb.ports | toYaml | nindent 2 }}