apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-dmarc-analyzer.fullname" . }}-mariadb-secret
  labels:
  {{- include "open-dmarc-analyzer.labels" . | nindent 4 }}
data:
  MARIADB_DATABASE: {{ .Values.mariadb.config.mariadbDatabase | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.config.mariadbPassword | b64enc | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.config.mariadbRootPassword | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.config.mariadbUser | b64enc | quote }}