apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-dmarc-analyzer.fullname" . }}-mariadb-pvc
  labels:
    io.kompose.service: mariadb-pvc
  {{- include "open-dmarc-analyzer.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mariadbPvc.storageRequest | quote }}