apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-dmarc-analyzer.fullname" . }}-parser-secret
  labels:
  {{- include "open-dmarc-analyzer.labels" . | nindent 4 }}
data:
  DBHOST: {{ printf "%s-mariadb" (include "open-dmarc-analyzer.fullname" .) | b64enc | quote }}
  DBNAME: {{ .Values.mariadb.config.mariadbDatabase | b64enc | quote }}
  DBPASS: {{ .Values.mariadb.config.mariadbPassword | b64enc | quote }}
  DBUSER: {{ .Values.mariadb.config.mariadbUser | b64enc | quote }}
  IMAPAUTH: {{ .Values.parser.config.imapauth | b64enc | quote }}
  IMAPDMARCERR: {{ .Values.parser.config.imapdmarcerr | b64enc | quote }}
  IMAPDMARCFOLDER: {{ .Values.parser.config.imapdmarcfolder | b64enc | quote }}
  IMAPDMARCPROC: {{ .Values.parser.config.imapdmarcproc | b64enc | quote }}
  IMAPIGNOREERROR: {{ .Values.parser.config.imapignoreerror | b64enc | quote }}
  IMAPPASS: {{ .Values.parser.config.imappass | b64enc | quote }}
  IMAPPORT: {{ .Values.parser.config.imapport | b64enc | quote }}
  IMAPSERVER: {{ .Values.parser.config.imapserver | b64enc | quote }}
  IMAPSSL: {{ .Values.parser.config.imapssl | b64enc | quote }}
  IMAPUSER: {{ .Values.parser.config.imapuser | b64enc | quote }}